language: node_js
node_js:
  - '10'
  - '11'
  - '12'
install:
  - npm install -q --no-color --no-progress
before_script:
  - npm install codeclimate-test-reporter -g
script:
  - npm run lint
  - npm run test
after_success:
  - codeclimate-test-reporter < ./__tests__/coverage/lcov.info
